### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'ModelMetaclass'

### ISSUE THREAD

**Issue by aminebizid** [pydantic/pydantic-ai#605]
I get this error 
unsupported operand type(s) for |: 'ModelMetaclass' and 'ModelMetaclass'

```python
# This agent is responsible for controlling the flow of the conversation.
search_agent = Agent[Deps, FlightDetails | NoFlightFound](
    'ollama:llama3.2:3b',
    result_type=FlightDetails | NoFlightFound,  # type: ignore
    retries=4,
    system_prompt=(
        'Your job is to find the cheapest flight for the user on the given date. '
    ),
)
```

```toml
[project]
name = "pa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic-ai>=0.0.17",
    "pydantic-ai-slim>=0.0.17",
    "rich>=13.9.4",
]
```
